name: sijemur
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_auth_web: ^5.13.2
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.0
  http: ^0.13.5
  cloud_firestore: ^5.4.4
  image_picker: ^0.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pngtree-blue-washing-machine-for-laundry-logo-png-image_8517358.png
