// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcz3od1qsqJnsycX2AF7A_BjyyNxLTC0',
    appId: '1:444161178281:web:861f234ef13764d60247b8',
    messagingSenderId: '444161178281',
    projectId: 'trial-cf95f',
    authDomain: 'trial-cf95f.firebaseapp.com',
    storageBucket: 'trial-cf95f.appspot.com',
    measurementId: 'G-H8KBH3T0N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXrPwVUeYsjN7d5TCxmRwOjhJXYyo5uM',
    appId: '1:444161178281:android:ec5595e95d4079830247b8',
    messagingSenderId: '444161178281',
    projectId: 'trial-cf95f',
    storageBucket: 'trial-cf95f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNxIsApvprOW_R9wlM5rqrPO_csFQndQ',
    appId: '1:444161178281:ios:7f72fb7d638a71d30247b8',
    messagingSenderId: '444161178281',
    projectId: 'trial-cf95f',
    storageBucket: 'trial-cf95f.appspot.com',
    iosBundleId: 'com.example.laundryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhNxIsApvprOW_R9wlM5rqrPO_csFQndQ',
    appId: '1:444161178281:ios:7f72fb7d638a71d30247b8',
    messagingSenderId: '444161178281',
    projectId: 'trial-cf95f',
    storageBucket: 'trial-cf95f.appspot.com',
    iosBundleId: 'com.example.laundryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGcz3od1qsqJnsycX2AF7A_BjyyNxLTC0',
    appId: '1:444161178281:web:4827921501fea6780247b8',
    messagingSenderId: '444161178281',
    projectId: 'trial-cf95f',
    authDomain: 'trial-cf95f.firebaseapp.com',
    storageBucket: 'trial-cf95f.appspot.com',
    measurementId: 'G-SSR9K3EN09',
  );
}
